# Generated by Django 4.1.3 on 2024-01-30 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itineraryapi', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('description', models.TextField(max_length=50)),
                ('length_of_time', models.CharField(max_length=25)),
                ('cost', models.IntegerField()),
            ],
        ),
    ]
