# Generated by Django 4.1.3 on 2024-02-03 17:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('itineraryapi', '0006_alter_tripactivity_trip'),
    ]

    operations = [
        migrations.CreateModel(
            name='TripReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review', models.CharField(max_length=150)),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='itineraryapi.trip')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trip_reviews', to='itineraryapi.admin')),
            ],
        ),
    ]
