# Generated by Django 4.1.3 on 2024-02-03 17:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('itineraryapi', '0007_tripreview'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tripreview',
            name='trip',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trip_reviews', to='itineraryapi.trip'),
        ),
        migrations.AlterField(
            model_name='tripreview',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='itineraryapi.admin'),
        ),
    ]
