# Generated by Django 4.1.3 on 2024-02-03 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itineraryapi', '0009_destination_alter_trip_destination'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='destination',
            field=models.CharField(max_length=50),
        ),
        migrations.DeleteModel(
            name='Destination',
        ),
    ]
